In [33]:
import math
import numpy as np
from numpy.linalg import inv
from spatialmath import SO2, SE2

# SO(2) - Rotation

In [34]:
r1 = SO2(-math.pi/2)
print("R1")
print(r1)

R1
   0         1         
  -1         0         



In [35]:
r2 = SO2(90, unit='deg')
print("R2")
print(r2)

R2
   0        -1         
   1         0         



In [36]:
a = np.array([1, 0])
b = r1 * a
print(b)

[[ 6.123234e-17]
 [-1.000000e+00]]


In [37]:
# Numpy inv() generates a numpy arr, so we use @ (or numpy.matmul()) instead
c = inv(r1) @ a
print(c)

[6.123234e-17 1.000000e+00]


# SE(2)

In [38]:
h_1 = SE2(math.pi/2)
print('H1:')
print(h_1)

H1:
   0        -1         0         
   1         0         0         
   0         0         1         



In [39]:
h_2 = SE2(
    x=1,
    y=2,
)
print('H2:')
print(h_2)

H2:
   1         0         1         
   0         1         2         
   0         0         1         



In [40]:

h_3 = h_1 * h_2
print('H3:')
print(h_3)

H3:
   0        -1        -2         
   1         0         1         
   0         0         1         



In [41]:

h_4 = h_2 * h_1
print('H4:')
print(h_4)

H4:
   0        -1         1         
   1         0         2         
   0         0         1         



In [42]:
m = [1, 0, 1]

r_1 = inv(h_1) @ m
(r_1)

array([ 6.123234e-17, -1.000000e+00,  1.000000e+00])

In [43]:
r_2 = inv(h_2) @ m
(r_2)

array([ 0., -2.,  1.])

In [44]:
r_3 = inv(h_3) @ m
(r_3)

array([-1., -3.,  1.])

# SO(3): rotation in 3D

In [45]:
from spatialmath import SO3, SE3

Create a rotation matrix $R_x$ representing $\pi/2$ rad rotation around the $x$ axis.

In [46]:
r_x = SO3.Rx(math.pi/2)
(r_x)

   1         0         0         
   0         0        -1         
   0         1         0         


Create a rotation matrix $R_y$ representing $\pi/2$ rad rotation around the $y$ axis.

In [47]:
r_y = SO3.Ry(math.pi/2)
(r_y)

   0         0         1         
   0         1         0         
  -1         0         0         


Create a rotation matrix $R_z$ representing $\pi/2$ rad rotation around the $z$ axis.

In [48]:
r_z = SO3.Rz(math.pi/2)
(r_z)

   0        -1         0         
   1         0         0         
   0         0         1         


Create a rotation matrix $R_{xyz}$ representing three $\pi/2$ rad rotations around the $x$, $y$, and $z$ axes in that order.

In [49]:
r_xyz = r_x * r_y * r_z
(r_xyz)

   0         0         1         
   0        -1         0         
   1         0         0         


Create a rotation matrix $R_{xzy}$ representing three $\pi/2$ rad rotations around the $x$, $z$, and $y$ axes in that order.

In [50]:
r_xzy = r_x * r_z * r_y
(r_xzy)

   0        -1         0         
   1         0         0         
   0         0         1         


In [51]:
r_rpy = SO3.RPY(math.pi/2, math.pi/2, math.pi/2)
(r_rpy)

   0         0         1         
   0         1         0         
  -1         0         0         


In [52]:
r_eul = SO3.Eul(math.pi/2, math.pi/2, math.pi/2)
(r_eul)

  -1         0         0         
   0         0         1         
   0         1         0         


# SE(3)

Create an homogenous matrix $H_{tx}$ representing a 1 m translation along the $x$ axis.

In [53]:
h_tx = SE3.Tx(1)
(h_tx)

   1         0         0         1         
   0         1         0         0         
   0         0         1         0         
   0         0         0         1         


Create an homogenous matrix $H_{ty}$ representing a 2 m translation along the $y$ axis.

In [54]:
h_ty = SE3.Ty(2)
(h_ty)

   1         0         0         0         
   0         1         0         2         
   0         0         1         0         
   0         0         0         1         


Create an homogenous matrix $H_{tz}$ representing a 3 m translation along the $z$ axis.

In [55]:
h_tz = SE3.Tz(3)
(h_tz)

   1         0         0         0         
   0         1         0         0         
   0         0         1         3         
   0         0         0         1         


Create an homogenous matrix $H_t$ representing three 1, 2, and 3 m translations along the $x$, $y$, and $z$ axes in that order.

In [56]:
h_t = h_tx * h_ty * h_tz
(h_t)

   1         0         0         1         
   0         1         0         2         
   0         0         1         3         
   0         0         0         1         


Compute the new coordinates of $a = [1, 0, 0]$ after three 1, 2, and 3 m translations along the $x$, $y$, and $z$ axes in that order.

In [57]:
a = [1, 0, 0, 1]

In [58]:
a3 = inv(h_t) @ a
(a3)

array([ 0., -2., -3.,  1.])

Create an homogenous matrix $H_r$ representing a $\pi/2$ rad rotation around the $x$ axis

In [59]:
h_r = SE3.Rx(math.pi/2)
(h_r)

   1         0         0         0         
   0         0        -1         0         
   0         1         0         0         
   0         0         0         1         


Compute the new coordinates of $a = [1, 0, 0]$ after three 1, 2, and 3 m translations along the $x$, $y$, and $z$ axis and one $\pi/2$ rad rotation around the $x$ axis.

In [63]:
h_tr = h_t * h_r

a_res = inv(h_tr) @ a
(a_res)

array([ 0., -3.,  2.,  1.])