In [3]:
# imports
import torch
import numpy as np

In [ ]:
import os
import random
import numpy as np
import torch

def set_seed(seed):
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    # Leave as True to ensure deterministic behavior.
    torch.use_deterministic_algorithms(False)
    np.random.seed(seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

set_seed(42)

In [2]:
T = torch.tensor([[1, 2], [3, 4]])
T

tensor([[1, 2],
        [3, 4]])

In [4]:
A = torch.zeros((3, 3))
A

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
B = torch.ones((3, 3))
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [9]:
v = torch.tensor([[1], [2], [3]], dtype=torch.float32)

v, I @ v

(tensor([[1.],
         [2.],
         [3.]]),
 tensor([[1.],
         [2.],
         [3.]]))

In [10]:
torch.rand((3, 3))

tensor([[0.7960, 0.0204, 0.7002],
        [0.8637, 0.1043, 0.2668],
        [0.6748, 0.9047, 0.0666]])

In [11]:
torch.randn((3, 3))

tensor([[-0.2179,  0.5449, -1.0085],
        [-0.7483, -1.9127, -1.4410],
        [-0.2582,  0.8042,  0.2454]])

In [12]:
mu = 5
sigma = 1
N = torch.normal(mu, sigma, (100, 100))

torch.mean(N), torch.std(N)

(tensor(4.9842), tensor(1.0009))

In [13]:
torch.zeros_like(A), torch.ones_like(B), torch.rand_like(A)

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0.7282, 0.6711, 0.3839],
         [0.0759, 0.7174, 0.9517],
         [0.7424, 0.9942, 0.8717]]))

In [14]:
T.dtype, T.shape, T.device

(torch.int64, torch.Size([2, 2]), device(type='cpu'))

In [15]:
E = torch.rand((24, 3, 128, 128))

E.shape, torch.transpose(E, 1, 3).shape, torch.permute(E, (0, 2, 3, 1)).shape

(torch.Size([24, 3, 128, 128]),
 torch.Size([24, 128, 128, 3]),
 torch.Size([24, 128, 128, 3]))

In [19]:
E[:, 0], E[0, :]

(tensor([[[0.5128, 0.1570, 0.0850,  ..., 0.1270, 0.5248, 0.3922],
          [0.2032, 0.6623, 0.5437,  ..., 0.1499, 0.0232, 0.4865],
          [0.8346, 0.4636, 0.9492,  ..., 0.0809, 0.9027, 0.3325],
          ...,
          [0.2861, 0.7658, 0.8274,  ..., 0.5432, 0.7543, 0.9152],
          [0.0500, 0.3290, 0.4225,  ..., 0.4535, 0.9524, 0.4407],
          [0.2254, 0.9594, 0.5365,  ..., 0.0650, 0.4904, 0.6302]],
 
         [[0.9549, 0.2920, 0.9357,  ..., 0.2303, 0.6503, 0.6622],
          [0.9316, 0.7518, 0.0015,  ..., 0.0059, 0.0056, 0.5936],
          [0.9588, 0.3701, 0.2780,  ..., 0.4043, 0.1662, 0.8489],
          ...,
          [0.9248, 0.2545, 0.6792,  ..., 0.4049, 0.8166, 0.9896],
          [0.3666, 0.2271, 0.0112,  ..., 0.6541, 0.7323, 0.8564],
          [0.6120, 0.7074, 0.3422,  ..., 0.4304, 0.9405, 0.3390]],
 
         [[0.9161, 0.5858, 0.3810,  ..., 0.2885, 0.5190, 0.7532],
          [0.7253, 0.7665, 0.0544,  ..., 0.9821, 0.6299, 0.8789],
          [0.9171, 0.9168, 0.0014,  ...,

In [20]:
torch.flip(E[0, :], dims=(0,))

tensor([[[0.6865, 0.7923, 0.8910,  ..., 0.8921, 0.0713, 0.5715],
         [0.0387, 0.7427, 0.9071,  ..., 0.9444, 0.6077, 0.8362],
         [0.2931, 0.8521, 0.3672,  ..., 0.7017, 0.1716, 0.9100],
         ...,
         [0.5080, 0.9141, 0.2970,  ..., 0.5361, 0.3020, 0.6764],
         [0.8275, 0.6963, 0.8602,  ..., 0.5294, 0.7749, 0.6636],
         [0.8905, 0.1038, 0.4816,  ..., 0.4163, 0.0754, 0.7881]],

        [[0.3703, 0.8470, 0.1977,  ..., 0.0101, 0.0883, 0.4405],
         [0.1563, 0.8297, 0.5421,  ..., 0.3489, 0.6247, 0.7128],
         [0.7583, 0.7536, 0.8562,  ..., 0.3658, 0.7888, 0.0030],
         ...,
         [0.5146, 0.8207, 0.9534,  ..., 0.0157, 0.8078, 0.8310],
         [0.9830, 0.1070, 0.2449,  ..., 0.0167, 0.2471, 0.7615],
         [0.2675, 0.3423, 0.6593,  ..., 0.4162, 0.8806, 0.1076]],

        [[0.5128, 0.1570, 0.0850,  ..., 0.1270, 0.5248, 0.3922],
         [0.2032, 0.6623, 0.5437,  ..., 0.1499, 0.0232, 0.4865],
         [0.8346, 0.4636, 0.9492,  ..., 0.0809, 0.9027, 0.

In [21]:
D = torch.rand((4, 4, 3))
torch.reshape(D, (4, 4 *3))

tensor([[0.7723, 0.9570, 0.8248, 0.1791, 0.0664, 0.9672, 0.3118, 0.0975, 0.7035,
         0.2473, 0.2263, 0.6516],
        [0.7881, 0.9218, 0.3057, 0.7873, 0.2708, 0.3634, 0.8278, 0.3273, 0.9376,
         0.7383, 0.2048, 0.6244],
        [0.0320, 0.6625, 0.8559, 0.5631, 0.3213, 0.2234, 0.1187, 0.2194, 0.7299,
         0.8566, 0.8498, 0.6443],
        [0.0412, 0.8220, 0.4762, 0.9876, 0.4289, 0.5886, 0.1775, 0.2035, 0.0500,
         0.6195, 0.2570, 0.7293]])

In [22]:
torch.cuda.is_available()

False